### PR TITLE
Magento2 Quickstart improvements, fixes #2600, fixes #2602

### LINKED ISSUE #2600: Improve Magento 2 quickstart to deal with Elasticsearch requirement
**Describe the bug**
I installed ddev on my machine and used Magento 2 Quickstart steps to install latest Magento version but I got the error while setting up the magento.

**To Reproduce**

1. Go to 'Magento 2 Quickstart'
2. Run commands step by step
3. Run magento setup command `bin/magento setup:install  --db-host=db --db-name=db --db-user=db --db-password=db  --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com  --admin-user=admin --admin-password=admin123 --language=en_US`

**Expected behavior**
Magento setup should complete without any error

**Screenshots**

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version if on macOS or Windows: 2.5.0.0
- ddev version information: v1.15.3

**Additional context**
We need one more container for elasticsearch for Magento 2.4.x.
- You must install and configure Elasticsearch 7.6.x before upgrading to Magento 2.4.x.
- Magento 2.4.x is tested with Elasticsearch 7.6.x only. You can use other 7.x versions at your discretion, but we recommend using the tested version of Elasticsearch.
- [More info here](https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html)

### LINKED ISSUE #2602: Magento 2 Quickstart: PHP outdated
**Describe the bug**
I just tried to follow the [Magento 2 Quickstart](https://ddev.readthedocs.io/en/stable/users/cli-usage/#magento-2-quickstart) but it's not possible since the PHP version is outdated for the container `ddev-magento2-web` which is using php7.2

Error: `magento/product-community-edition 2.4.1 requires php ~7.3.0||~7.4.0 -> your PHP version (7.2.32) does not satisfy that requirement.`

**To Reproduce**

1. Go to https://ddev.readthedocs.io/en/stable/users/cli-usage/#magento-2-quickstart
2. Follow steps:

```sh
mkdir ddev-magento2 && cd ddev-magento2
ddev config --project-type=magento2 --docroot=pub --create-docroot
ddev start
ddev composer create --repository=https://repo.magento.com/ magento/project-community-edition
```
Last one will fail because of outdated php version

**Expected behavior**
I expect the quickstart guide to work without any errors.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10
- Docker Desktop version: 2.5.0.0 (49427)
- ddev version information:
```
DDEV-Local version      v1.15.3
commit                  v1.15.3
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1
docker                  19.03.13
docker-compose          1.25.0-rc4
os                      linux
router                  drud/ddev-router:v1.15.1
web                     drud/ddev-webserver:v1.15.3
```
- config.yaml contents for the misbehaving project:
```
name: magento2
type: magento2
docroot: pub
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true

... only comments below here ...
```
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
Nope, none.

**Additional context**
I'm able to fix it, but the quickstart guide should work out of the box, shouldn't it.

### PR DESCRIPTION
**Pull request by Morgy93**
## The Problem/Issue/Bug:
- The Magento2 DevDoc links are outdated (version 2.3 instead of 2.4)
- The Magento 2 Quickstart doesn't work with latest Magento 2.4.1 version because of missing elasticsearch.
- Added Magento 2 base-url to the install command instead of running it manually afterwards and having to flush the cache.
- The magento2 project type doesn't work with latest Magento 2.4.1 because it runs with php7.2 which is not supported

## How this PR Solves The Problem:
I added missing elasticsearch from ddev-contrib to the doc
https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/elasticsearch

I removed `magento2ConfigOverrideAction` from the magento2 project type to use standard php7.3 which is minimum requirement for Magento 2.4.1

## Manual Testing Instructions:
Just folow the Magento 2 Quickstart.

## Automated Testing Overview:
It would be awesome to cover all quickstarts with automated tests, but I couldn't find any solution to this in this repo.

## Related Issue Link(s):
#2600 
#2602

### CODE REVIEW

**Comment by rfay** [comment]
Failure in tests is
```
+ make test
  | building .gotmp/bin/darwin_amd64/ddev from ./cmd/... ./pkg/...
  | # github.com/drud/ddev/pkg/ddevapp
  | pkg/ddevapp/apptypes.go:95:237: undefined: magento2ConfigOverrideAction
```

You probably just have to remove magento2ConfigOverrideAction in apptypes.go

It's not hard to build it yourself and test, https://github.com/drud/ddev/blob/master/docs/developers/building-contributing.md

**Comment by Morgy93** [comment]
Too greedy here, should've opened two separate PR for docs and code 🙈 

I only read through https://github.com/drud/ddev/blob/master/CONTRIBUTING.md which doesn't mention contribution to docs at all.
Sadly I cannot change branch name to your convention without opening another PR. 😒

**Comment by rfay** [comment]
I certainly didn't think it was greedy! I thought it was *ambitious* and so very much appreciated! You did the docs just right.

There's no need to worry about the branch name. It's no big deal. 

Congrats on the tests passing! I guess we should consider changing the full test to use Magento as well, but that can wait for now.

**Review by rfay — APPROVED** [review]
Just went through the new version with no trouble. Thanks!

**Comment by rfay** [comment]
@Morgy93 I just ran through a test install, and after going through this I got unstyled HTML with lots of 404's for almost all static assets. Could you run through it again please or tell me what I did wrong? 

https://ddev.readthedocs.io/en/latest/users/cli-usage/#magento-2-quickstart

**Comment by Morgy93** [comment]
@rfay I am unable to reproduce it just now. 
It might be due to wrong permissions or things over here:
[After installing, images and stylesheets do not load; only text displays, no graphics - support.magento.com](https://support.magento.com/hc/en-us/articles/360032994352)

**Comment by rfay** [comment]
So you're saying you were able to work through the quickstart with no problems @Morgy93 ? Thanks so much for testing that.
